<?php
/**
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2011-2012 Sergey Storchay <r8@r8.com.ua>
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

    $_mode  = Mage::helper('background')->getBackgroundMode();
    $_image = Mage::helper('background')->getBackgroundImage();
?>
<?php if ($_mode != 'none' && $_image): ?>
    <?php
        $_imageUrl = Mage::helper('background')->getBaseMediaUrl() . '/' . $_image;
    ?>
    <style type="text/css">
        body {
            background: url(<?php echo $_imageUrl ?>) top center no-repeat;
        }
    </style>
<?php endif;?>
