<?php
/**
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2011-2012 Sergey Storchay <r8@r8.com.ua>
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

    /** @var $_helper Magemaven_Background_Helper_Data */
    $_helper = Mage::helper('background');

    $_mode  = $_helper->getBackgroundMode();
    $_image = $_helper->getBackgroundImage();
?>
<?php if ($_mode != Magemaven_Background_Model_Source_Mode::MODE_NONE && $_image): ?>
    <?php
        $_imageUrl = $_helper->getBaseMediaUrl() . '/' . $_image;

        switch ($_mode) {
            case Magemaven_Background_Model_Source_Mode::MODE_TOP_CENTER:
                $_backgroundOptions = 'top center no-repeat';
                break;
            case Magemaven_Background_Model_Source_Mode::MODE_REPEAT:
                $_backgroundOptions = 'repeat';
                break;
            default:
                $_backgroundOptions = '';
        }
    ?>
    <style type="text/css">
        body {
            background: url(<?php echo $_imageUrl ?>) <?php echo $_backgroundOptions ?>;
        }
    </style>
<?php endif;?>
